# Generated by Django 3.0.4 on 2020-04-03 13:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifications',
            name='all_datas',
            field=jsonfield.fields.JSONField(),
        ),
    ]
